### ISSUE TITLE
Improve export and importing stats

### ISSUE THREAD

**Issue by JohnAkerman** [JohnAkerman/TabStats#2]
Currently the export stats function is broken due to my selectors, I do feel like we need to revamp how the export feature works. 

## Exporting
Currently we can only export stats and it needs a rework, ideally the output of the tool looks a bit nicer, perhaps we can introduce automatic copy to the clipboard for improved user experience.
### Send Via Email
It could be a nice option to include a way of sending the export via email, perhaps as a JSON file attachment or just using plaintext.

## Importing
We also need the ability to import stats (using exported datastring). This will be useful for people to keep stats cross multiple computers up to date and would allow us to easily import test data.

**Comment by JohnAkerman** [comment]
PR #11 has fixed the export feature. Many thanks @SolidusMaximus

**Comment by SolidusMaximus** [comment]
Progress and Todos

- [x] Restore broken export
- [x] Add import
- [ ] Add export to email or a cloud storage service
- [x] Clean up export look and feel (try adding export to file)

**Comment by SolidusMaximus** [comment]
Most probably going to use validate.js to validate the JSON given from import
https://validatejs.org/

**Comment by JohnAkerman** [comment]
I have now added drag and drop support for JSON files so the file can be dragged over and imported. This is in changeset https://github.com/JohnAkerman/TabStats/commit/f76a83e635acd1bd014441abbd1d2b92ba5d84b4

![image](https://user-images.githubusercontent.com/2814624/32920292-a3eb68a6-cb20-11e7-9b84-89b95fba17af.png)

**Comment by JohnAkerman** [comment]
So I feel this task is now complete, the last item on this could be considered an enhancement:
- [ ] Add export to email or a cloud storage service
- [x] Add estimate of storage size

**Comment by JohnAkerman** [comment]
Ideas have been added to #19
